name: Deploy to Posit Connect

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.4'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Deploy to Posit Connect
        env:
          POSIT_API_KEY: ${{ secrets.POSIT_API_KEY }}
        run: ./scripts/deploy_wisc.sh
